### ISSUE TITLE
liquid カスタマイズの項目追加

### ISSUE THREAD

**Issue by Tsubasa-M0307** [Tsubasa-M0307/liquid#11]
リンクの項目追加

**multicolumn.liquid**

liquid

```html
<li class="multicolumn-card">
{%- if block.settings.card_link != blank -%}
  <a href="{{block.settings.card_link}}" class="card_link"></a>
{%- endif -%}
~項目~
</li>

{% schema %}
{
"blocks": [
    {
      "type": "column",
      "name": "t:sections.multicolumn.blocks.column.name",
      "settings": [
				{
          "type": "url",
          "id": "card_link",
          "label": "カード全体のリンク"
        },
			]
    }
  ],
}
```

css

liのカラムに対して上からかぶせるようにリンクを乗せる。

```css
.multicolumn-card{
	position:relative;
}

.card_link{
  position: absolute;
  top: 0;
  left: 0;
  display: block;
  width: 100%;
  height: 100%;
  z-index: 3;
  transition:.3s;
}

.card_link:hover{
	opacity: .3;
  background: #fff;
}
```
